# Файл: ~/.config/alacritty/themes/everforest-dark.toml
[colors.primary]
background = '#22282c'
foreground = '#988f7b'

[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.dim]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#dfddd2'

[colors.cursor]
cursor = '#d3c6aa'
text   = '#2f383e'

[colors.selection]
text       = '#2f383e'
background = '#a7c080'

[colors.search.matches]
foreground = '#2f383e'
background = '#dbbc7f'

[colors.search.focused_match]
foreground = '#2f383e'
background = '#a7c080'

[colors.footer_bar]
background = '#3c474d'
foreground = '#d3c6aa'
