general.import = ["~/.config/alacritty/themes/everforest-dark.toml"]

[env]
TERM = "xterm-256color"

[font]

# Uncomment after install_nerd_font.sh
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }
size = 12

[window]
padding.x = 2
padding.y = 2
# Uncomment on hypr
# decorations = "None"

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]
